api-addr: :10000
p2p-addr: :10002
debug-api-addr: :10002
password: ""
swap-endpoint: ws://localhost:8546 
debug-api-enable: true
swap-initial-deposit: "1000000000000000"
bootnode:
- /dnsaddr/bootnode.ethswarm.org
bootnode-mode: false
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
config: ./.bee.yaml
cors-allowed-origins: []
data-dir: ./.bee
db-block-cache-capacity: "33554432"
db-capacity: "5000000"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
gateway-mode: false
global-pinning-enable: false
help: false
nat-addr: ""
network-id: "1"
p2p-quic-enable: false
p2p-ws-enable: false
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"
resolver-options: []
standalone: false
swap-enable: true
swap-factory-address: ""
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: bee
verbosity: info
welcome-message: ""
