api-addr: :1653
p2p-addr: :1654
debug-api-addr: :1655
password: ""
swap-endpoint: ws://localhost:8546
cache-capacity: "1000000"
swap-initial-deposit: "1000000000000000"
config: ./.bee.yaml
data-dir: ./.bee
full-node: true
cors-allowed-origins: []
block-time: "15"
bootnode:
- /dnsaddr/bootnode.ethswarm.org
bootnode-mode: false
clef-signer-enable: false
clef-signer-endpoint: ""
clef-signer-ethereum-address: ""
db-block-cache-capacity: "33554432"
db-disable-seeks-compaction: false
db-open-files-limit: "200"
db-write-buffer-size: "33554432"
debug-api-enable: true
gateway-mode: false
global-pinning-enable: false
help: false
nat-addr: ""
network-id: "1"
p2p-quic-enable: false
p2p-ws-enable: false
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "10000000000000"
postage-stamp-address: ""
resolver-options: []
standalone: false
swap-enable: true
swap-factory-address: ""
swap-legacy-factory-addresses: []
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: bee
transaction: ""
verbosity: info
welcome-message: ""
